/*
 * generated by Xtext
 */
package de.htwdd.sf.beleg.s74838;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PrologRuntimeModule extends de.htwdd.sf.beleg.s74838.AbstractPrologRuntimeModule {

}
