/*
 * generated by Xtext
 */
package de.htwdd.sf.beleg.s74838.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.htwdd.sf.beleg.s74838.ui.internal.PrologActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PrologExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PrologActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PrologActivator.getInstance().getInjector(PrologActivator.DE_HTWDD_SF_BELEG_S74838_PROLOG);
	}
	
}
