/**
 * generated by Xtext
 */
package de.htwdd.sf.beleg.s74838.validation;

import de.htwdd.sf.beleg.s74838.validation.AbstractPrologValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class PrologValidator extends AbstractPrologValidator {
}
