/*
* generated by Xtext
*/
package de.htwdd.sf.beleg.s74838;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PrologUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.htwdd.sf.beleg.s74838.ui.internal.PrologActivator.getInstance().getInjector("de.htwdd.sf.beleg.s74838.Prolog");
	}
	
}
