/*
 * generated by Xtext
 */
package de.htwdd.sf.beleg.s74838.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractPrologValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.htwdd.sf.beleg.s74838.prolog.PrologPackage.eINSTANCE);
		return result;
	}
}
