/*
* generated by Xtext
*/
package de.htwdd.sf.beleg.s74838.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.htwdd.sf.beleg.s74838.services.PrologGrammarAccess;

public class PrologParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PrologGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.htwdd.sf.beleg.s74838.parser.antlr.internal.InternalPrologParser createParser(XtextTokenStream stream) {
		return new de.htwdd.sf.beleg.s74838.parser.antlr.internal.InternalPrologParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PrologDsl";
	}
	
	public PrologGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PrologGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
