/*
* generated by Xtext
*/
package de.htwdd.sf.beleg.s74838.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PrologAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/htwdd/sf/beleg/s74838/parser/antlr/internal/InternalProlog.tokens");
	}
}
