/*
 * generated by Xtext
 */
package de.htwdd.sf.beleg.s74838.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PrologUiModule extends de.htwdd.sf.beleg.s74838.ui.AbstractPrologUiModule {
	public PrologUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
