/**
 * generated by Xtext
 */
package de.htwdd.sf.beleg.s74838.ui.labeling;

import com.google.inject.Inject;
import de.htwdd.sf.beleg.s74838.prolog.Atom;
import de.htwdd.sf.beleg.s74838.prolog.Clause;
import de.htwdd.sf.beleg.s74838.prolog.Exquery;
import de.htwdd.sf.beleg.s74838.prolog.Fact;
import de.htwdd.sf.beleg.s74838.prolog.Folge;
import de.htwdd.sf.beleg.s74838.prolog.List;
import de.htwdd.sf.beleg.s74838.prolog.NotEmptyList;
import de.htwdd.sf.beleg.s74838.prolog.Predicate;
import de.htwdd.sf.beleg.s74838.prolog.Program;
import de.htwdd.sf.beleg.s74838.prolog.PrologDsl;
import de.htwdd.sf.beleg.s74838.prolog.Query;
import de.htwdd.sf.beleg.s74838.prolog.Rule;
import de.htwdd.sf.beleg.s74838.prolog.Term;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class PrologLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public PrologLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final PrologDsl dsl) {
    return "Prolog";
  }
  
  public String text(final Program ele) {
    return "Program";
  }
  
  public String text(final Exquery ele) {
    return "Execute Query";
  }
  
  public String text(final Query ele) {
    return "Query";
  }
  
  public String text(final Clause ele) {
    return "Clause";
  }
  
  public String text(final Fact ele) {
    return "Fact";
  }
  
  public String text(final Rule ele) {
    return "Rule";
  }
  
  public String text(final Predicate ele) {
    return "Predicate";
  }
  
  public String text(final Term ele) {
    return "Term";
  }
  
  public String text(final Atom ele) {
    String _atom = ele.getAtom();
    return ("Atom =" + _atom);
  }
  
  public String text(final List ele) {
    return "List";
  }
  
  public String text(final NotEmptyList ele) {
    return "NotEmptyList";
  }
  
  public String text(final Folge ele) {
    return "Folge";
  }
}
