/*
* generated by Xtext
*/
package de.htwdd.sf.beleg.s74838.ui.contentassist;

import de.htwdd.sf.beleg.s74838.ui.contentassist.AbstractPrologProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PrologProposalProvider extends AbstractPrologProposalProvider {

}
