/*
 * generated by Xtext
 */
package de.htwdd.sf.beleg.s74838.ui.contentassist

import de.htwdd.sf.beleg.s74838.ui.contentassist.AbstractPrologProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PrologProposalProvider extends AbstractPrologProposalProvider {
}
