/*
* generated by Xtext
*/
package de.htwdd.sf.beleg.s74838.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class PrologOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
