/**
 * generated by Xtext
 */
package de.htwdd.sf.beleg.s74838.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class PrologQuickfixProvider extends DefaultQuickfixProvider {
}
